# Site settings
title: Mark Angrish
email: mark.angrish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The thoughts, letters and articles of Mark Angrish. 
  Enjoys solving problems regarding people, politics and software.
  Loves learning new things. Founder of https://www.innerloop.io.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: markangrish
github_username:  mangrish
highlighter: pygments
github: [Repository metadata]

# Build settings
markdown: kramdown
